### DISCUSSION TITLE
Docker-Compose

### DISCUSSION THREAD

**Discussion by CptHowdy2012** [spacebin-org/spirit#440] [Feature Requests]
List a Docker-Compose file containing the proper recommended Postgresql setup?

**Comment by CptHowdy2012** [comment]
I started one but cant seem to get it to work, here is the compose file and the error from the log:

```dockerfile
------------------------------------------------------------------------------------
version: '3.8'

services:
  spacebin:
    image: spacebinorg/spirit
    container_name: spacebin
    ports:
      - "9998:9000"
    environment:
      - SPIRIT_PORT=9000
      - SPIRIT_CONNECTION_URI="postgres://user:password@postgres:5432/spacebin"
    depends_on:
      - postgres
    networks:
      - spacebin-network

  postgres:
    image: postgres:13-alpine
    container_name: postgres
    environment:
      - POSTGRES_DB=spacebin
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    volumes:
      - spacebin_postgres_data:/var/lib/postgresql/data
    networks:
      - spacebin-network

volumes:
  spacebin_postgres_data:

networks:
  spacebin-network:
    driver: bridge
------------------------------------------------------------------------------------
``` 

1:08AM FTL Failed migrations; Could not create DOCUMENTS tables. error="missing \"=\" after \"\\\"postgres://user:password@postgres:5432/spacebin\\\"\" in connection info string\""

**Reply by lukewhrit** [reply]
This is almost identical to the Docker Compose file used to host https://spaceb.in. Try formatting the environment variable like:
```
 environment:
      SPIRIT_CONNECTION_URI: postgresql://spacebin:password@spacebin_postgres:5432/spacebin?sslmode=disable
```


Since I no longer use Docker Compose to host Spacebin this file is a bit out of date, but may be helpful regardless.
```
version: '3.3'

services:
  spacebin_postgres:
    image: postgres:16.3-alpine
    restart: always
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=spacebin
      - POSTGRES_DB=spacebin
    volumes:
      - spacebin:/var/lib/postgresql/data
  spacebin:
    image: spacebinorg/spirit:v1.0.2
    restart: always
    environment:
      SPIRIT_CONNECTION_URI: postgresql://spacebin:password@spacebin_postgres:5432/spacebin?sslmode=disable
    ports:
      - 9000:9000
    depends_on:
      - spacebin_postgres
volumes:
    spacebin:
```
I am happy to add a section for this in the README.
